language: python

python:
  - "2.7"
  - "3.4"

install: false

branches:
  except:
    - develop

script: ./build.sh

deploy:
  - provider: releases
    api_key: '$GITHUB_API_KEY'
    file_glob: true
    file: "*.zip"
    skip_cleanup: true
    on:
      tags: true

  # - provider: pages
  #   api_key: '$GITHUB_API_KEY'
  #   file_glob: true
  #   file: "*.zip"
  #   skip_cleanup: true
  #   on:
  #     tags: true
